name: 📋 User story
description: User story to be added to our project backlog
title: "<Title>"
projects: ["Gauss-Robotics/8"]
# labels: ["Bug", "Needs Triage"]
body:
- type: textarea
  attributes:
    label: User story
    description: |
       examples:
       As a \<role\> I like to have \<capability\>, so that
       - benefit 1
       - benefit 2
       - ...
       
       As a \<role\> I can \<capability\>, so that \<receive benefit\>
       In order to \<receive benefit\> as a \<role\>, I can \<goal/desire\>
       As \<who\> \<when\> \<where\>, I want \<what\> because \<why\>
    value: As a
  validations:
    required: true
- type: textarea
  attributes:
    label: Acceptance criteria
    description: Criteria to be met before you accept the issue as fulfilled 
    placeholder: |       
       - [ ] User can...
       - [ ] I am able to...
       - [ ] ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: OPTIONALLY add further context and information, or tasks you think might be relevant
    placeholder: |
       - [ ] A
       - [ ] B       
  validations:
    required: false
